# Generated by Django 5.1.7 on 2025-03-12 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الطبيب')),
                ('email', models.EmailField(max_length=200, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=200, verbose_name='رقم الهاتف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='الصورة')),
                ('specialization', models.CharField(max_length=200, verbose_name='التخصص')),
                ('address', models.CharField(max_length=200, verbose_name='العنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'طبيب',
                'verbose_name_plural': 'الأطباء',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المريض')),
                ('email', models.EmailField(max_length=200, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=200, verbose_name='رقم الهاتف')),
                ('address', models.CharField(max_length=200, verbose_name='العنوان')),
                ('age', models.IntegerField(verbose_name='العمر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('diagnosis', models.TextField(verbose_name='التشخيص')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسجيل')),
                ('discharge_date', models.DateField(blank=True, null=True, verbose_name='الموعد المحدد ')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='managments.doctor', verbose_name='الطبيب المشرف')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
            },
        ),
    ]
