# Generated by Django 5.1.7 on 2025-03-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managments', '0002_doctor_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='rate',
        ),
    ]
