# Generated by Django 5.1.7 on 2025-03-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managments', '0004_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='العمر'),
        ),
    ]
